### ISSUE TITLE
Viewer plugin implementation/rollout metaticket

### ISSUE THREAD

**Issue by caffodian** [PolicyStat/ckeditor-plugin-autoid-headings#12]
It's now just more than an anchor!  See the trello card.  

https://trello.com/c/Nix6tjpH/31-editor-automatic-hyperlinkable-headings

Document issues/PRs used to actually implement the thing here.

**Comment by caffodian** [comment]
# TODO
- [x] placeholder version of viewer plugin with raw anchors (Seth did this when he was with us)
- [x] "finalize" the design 
- [x] pick a clipboard libs (the non-flash one https://clipboardjs.com/ seems "better", and we don't have to deal with the various cases when hiding the thing that zeroclipboard is stuck to)  
- [x] some form of test running
- [x] hash out the widget "template" (may not use an actual templating lib) - we have some odd separation of concerns here because templates are usually only in pstat
- [x] make it insert a link that displays the share widget instead
- [x] browser quirks (mostly for documentation) pass
- [ ] rollout

**Comment by caffodian** [comment]
I realized I hadn't actually given anyone repo permissions.  

I actually don't think this is that far away - really we just need to coordinate a bit on figuring out the design stuff.  And I need to stop getting tempted to over-complicate the widget templating.  There is no good reason for it to be a <component library flavour of the month> component

**Comment by caffodian** [comment]
@janasoroczak @winhamwr the TODO list above is my current take for what we need to actually do still.  If i missed anything please feel free to let me know.  We can coordinate the design and any additional stuff after standup tomorrow.

**Comment by caffodian** [comment]
Revisiting the clipboard stuff:

Zeroclipboard:
- fails with Flash disabled in IE11
- fails in all other browsers without Flash
- fails on Safari (mobile, desktop apparently works if you enable Flash)
- some issues around hiding/showing elements (there seem to be possible workarounds, but the actual stacktrace I ran into was inside Flash)

Clipboardjs:
- works in Chrome/Firefox
- gives a prompt on IE11
- if permission denied, still selects the field (and can display a mesage)
- fails in Safari but selects the field
- fails in IE8, selection seems inconsistent in the demo.  maybe some workarounds to this.  Not super worried.  

If i have mentally parsed this correctly, the only advantages of using ZeroClipboard would be IE8 with Flash and Safari with Flash.

**Comment by jms21852** [comment]
@caffiodian What sort of prompt does Clipboardjs give on IE11? (As IE11 users account for 80% of our traffic)

**Comment by caffodian** [comment]
This guy:  http://superuser.com/questions/476210/disable-do-you-want-to-allow-this-webpage-to-access-your-clipboard-message

**Comment by jms21852** [comment]
@caffodian Seems like Zeroclipboard is the better way to go. For browsers that have Flash disabled and on Safari, is there a way to hide the heading links altogether? Ideally if it's not going to work for them, better to hide it rather than show them a broken something that they cannot access.

**Comment by caffodian** [comment]
summarizing our hangouts discussion:
- use the javascript version after all - Flash benefits very few users, won't work on mobile, ever, etc. 
- If it fails, provide a popover similar to the current mockup (where there is an input box with the URL in it)
- if it succeeds, just display a tooltip saying it's copied to clipboard

@janasoroczak this is your requested reminder to update the mockup :)

**Comment by winhamwr** [comment]
With the current design, is there anything I can click that will "navigate me" to the link? That's how I use the [sphinx](http://jenkins.pstattest.com/job/pstat_master_sphinx_docs/Sphinx_Docs/development/back_end_guidelines/bulk_import_export.html#query-efficient) links and it's very efficient (for technical-ish) users. Not a must-have, but if we can incorporate that, I think it would be beneficial.

It provides a sense of transparency, I think. The user clicks the link, and their browser moves. If they were unsure exactly what the link did, that gives a visual demonstration.

**Comment by jms21852** [comment]
@winhamwr If the primary purpose of this functionality is to share, they're most likely going to then be pasting that link into an email, a chat, another browser window that's already open, another policy, etc. rather than open a link to the page they're already viewing.

**Comment by caffodian** [comment]
Some potential pre-launch things:

- fix the scroll jumping when clicking on the anchor (it is a side effect of the lazy way updating the address bar)
- implement feedback when actually copied
- lazy-create the popovers?  

I feel like 3rd is mostly pointless and minimal performance impact, but first and second are pretty annoying

**Comment by caffodian** [comment]
I also see the spec actually does have the "feedback when actually copied" thing.  :)
